import dotenv from 'dotenv';
dotenv.config();

import connectDB from './config/db.js';
import Product from './models/Product.js';

const products = [
  {
    name: 'Vitamin C 10% Face Serum',
    description: 'Dullness, Spots & Loss of Elasticity',
    detailedDescription: 'This powerful 10% Vitamin C serum is formulated with Ethyl Ascorbic Acid and Vitamin E to brighten dull skin, reduce dark spots, and improve skin elasticity. The lightweight, fast-absorbing formula works to even out skin tone and provide antioxidant protection against environmental damage.',
    price: 284,
    mrp: 349,
    discountPercentage: 19,
    category: 'Serum',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/products/Nia5BodyLotion1100-1-min.png?crop=center&height=960&v=1649958609&width=640',
    rating: 4.2,
    reviewCount: 127,
    keyBenefits: ['Brightens dull skin', 'Reduces dark spots', 'Improves skin elasticity', 'Antioxidant protection'],
    freeFrom: ['Fragrance', 'Sulphates', 'Parabens', 'Dyes', 'Phthalates'],
    certifications: ['Dermatologically Tested', 'Clinically Proven'],
    ingredients: ['Ethyl Ascorbic Acid 10%', 'Vitamin E', 'Hyaluronic Acid', 'Glycerin'],
    size: '30ml',
    specialFeatures: ['Non-comedogenic', 'Suitable for all skin types', 'Quick absorption'],
    bestSeller: true,
  },
  {
    name: 'Salicylic Acid 2% Face Serum',
    description: 'Acne, Oily Skin, Blackheads & Irritation',
    detailedDescription: 'Formulated with 2% Salicylic Acid (BHA), this serum penetrates deep into pores to unclog them, reduce acne, control oil production, and prevent blackheads. The non-irritating formula is suitable for oily and acne-prone skin types.',
    price: 237,
    mrp: 299,
    discountPercentage: 21,
    category: 'Serum',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/products/SalicylicAcid2_1200-1-min.png?crop=center&height=960&v=1646458899&width=640',
    rating: 4.5,
    reviewCount: 203,
    keyBenefits: ['Reduces acne', 'Controls oil', 'Unclogs pores', 'Prevents blackheads'],
    freeFrom: ['Fragrance', 'Sulphates', 'Parabens', 'Alcohol'],
    certifications: ['Dermatologically Tested', 'Non-comedogenic'],
    ingredients: ['Salicylic Acid 2%', 'Niacinamide', 'Zinc PCA', 'Allantoin'],
    size: '30ml',
    specialFeatures: ['Oil-free', 'Non-drying', 'Acne-fighting'],
    bestSeller: true,
  },
  {
    name: 'Salicylic Acid + LHA 2% Cleanser',
    description: 'Acne, Breakouts & Oiliness',
    detailedDescription: 'A powerful yet gentle cleanser with 2% Salicylic Acid and LHA (Lipo Hydroxy Acid) that effectively cleanses acne-prone skin, removes excess oil, and prevents breakouts without over-drying.',
    price: 284,
    mrp: 349,
    discountPercentage: 19,
    category: 'Cleanser',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SalicylicCleanserNew.jpg?crop=center&height=1260&v=1756796206&width=840',
    rating: 4.3,
    reviewCount: 156,
    keyBenefits: ['Fights acne', 'Controls oiliness', 'Prevents breakouts', 'Deep cleansing'],
    freeFrom: ['Fragrance', 'Sulphates', 'Parabens', 'Dyes'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Salicylic Acid 2%', 'LHA', 'Tea Tree Extract', 'Glycerin'],
    size: '100ml',
    specialFeatures: ['pH-balanced', 'Non-drying', 'Suitable for oily skin'],
    bestSeller: true,
  },
  {
    name: 'SPF 50 Sunscreen',
    description: 'Sun protection, UV exposure / damage',
    detailedDescription: 'Advanced broad-spectrum sunscreen with SPF 50 protection against UVA and UVB rays. The lightweight, non-greasy formula provides long-lasting protection without leaving a white cast. Perfect for daily use.',
    price: 379,
    mrp: 449,
    discountPercentage: 16,
    category: 'Sunscreen',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SPF50New.jpg?crop=center&height=960&v=1756795782&width=640',
    rating: 4.6,
    reviewCount: 289,
    keyBenefits: ['SPF 50 protection', 'Broad-spectrum', 'Non-greasy', 'No white cast'],
    freeFrom: ['Fragrance', 'Parabens', 'Oxybenzone', 'Octinoxate'],
    certifications: ['PA++++', 'Water-resistant'],
    ingredients: ['Zinc Oxide', 'Titanium Dioxide', 'Vitamin E', 'Niacinamide'],
    size: '50g',
    specialFeatures: ['Water-resistant', 'Non-comedogenic', 'Suitable for sensitive skin'],
    bestSeller: true,
  },
  {
    name: 'Hyaluronic Acid Moisturizer',
    description: 'Hydration, Dryness & Dehydration',
    detailedDescription: 'Intensive hydrating moisturizer with 2% Hyaluronic Acid that provides 48-hour moisture retention. The lightweight formula plumps skin, reduces fine lines, and leaves skin dewy and hydrated without feeling heavy.',
    price: 449,
    mrp: 549,
    discountPercentage: 18,
    category: 'Moisturizer',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/products/HAPGA2_1200-1-min.png?crop=center&height=960&v=1646395962&width=640',
    rating: 4.4,
    reviewCount: 198,
    keyBenefits: ['48-hour hydration', 'Plumps skin', 'Reduces fine lines', 'Non-greasy'],
    freeFrom: ['Fragrance', 'Parabens', 'Alcohol', 'Silicones'],
    certifications: ['Dermatologically Tested', 'Non-comedogenic'],
    ingredients: ['Hyaluronic Acid 2%', 'Glycerin', 'Ceramides', 'Squalane'],
    size: '50g',
    specialFeatures: ['Lightweight', 'Fast-absorbing', 'Suitable for all skin types'],
    bestSeller: true,
  },
  {
    name: 'Niacinamide 10% Serum',
    description: 'Oiliness, Pores & Uneven Texture',
    detailedDescription: 'Multi-benefit serum with 10% Niacinamide that controls excess oil production, minimizes the appearance of pores, smooths skin texture, and evens out skin tone. Suitable for all skin types.',
    price: 399,
    mrp: 499,
    discountPercentage: 20,
    category: 'Serum',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/products/Nia5BodyLotion1100-1-min.png?crop=center&height=960&v=1649958609&width=640',
    rating: 4.5,
    reviewCount: 234,
    keyBenefits: ['Controls oil', 'Minimizes pores', 'Smooths texture', 'Even skin tone'],
    freeFrom: ['Fragrance', 'Parabens', 'Alcohol', 'Dyes'],
    certifications: ['Dermatologically Tested', 'Non-comedogenic'],
    ingredients: ['Niacinamide 10%', 'Zinc PCA', 'Allantoin', 'Glycerin'],
    size: '30ml',
    specialFeatures: ['Oil-free', 'Lightweight', 'Quick absorption'],
    bestSeller: true,
  },
  {
    name: 'Gentle Foaming Cleanser',
    description: 'Daily cleansing, Sensitive skin',
    detailedDescription: 'pH-balanced daily cleanser that gently removes impurities, makeup, and excess oil without stripping the skin\'s natural moisture barrier. Ideal for sensitive and all skin types.',
    price: 349,
    mrp: 399,
    discountPercentage: 13,
    category: 'Cleanser',
    imageUrl: 'https://images.unsplash.com/photo-1608243810491-8b3f279ee840?w=500&h=500&fit=crop',
    rating: 4.3,
    reviewCount: 167,
    keyBenefits: ['Gentle cleansing', 'pH-balanced', 'Removes makeup', 'Maintains moisture'],
    freeFrom: ['Fragrance', 'Sulphates', 'Parabens', 'Soap'],
    certifications: ['Dermatologically Tested', 'Hypoallergenic'],
    ingredients: ['Glycerin', 'Aloe Vera', 'Chamomile Extract', 'Tocopherol'],
    size: '100ml',
    specialFeatures: ['Tear-free', 'Non-drying', 'Suitable for sensitive skin'],
    bestSeller: true,
  },
  {
    name: 'Retinol 0.3% Night Cream',
    description: 'Fine lines, Wrinkles & Anti-aging',
    detailedDescription: 'Advanced anti-aging night cream with 0.3% encapsulated Retinol that works overnight to reduce fine lines, wrinkles, and signs of aging. The slow-release formula minimizes irritation while maximizing effectiveness.',
    price: 699,
    mrp: 899,
    discountPercentage: 22,
    category: 'Treatment',
    imageUrl: 'https://images.unsplash.com/photo-1608243803803-4c4c0055e3b1?w=500&h=500&fit=crop',
    rating: 4.4,
    reviewCount: 145,
    keyBenefits: ['Reduces fine lines', 'Minimizes wrinkles', 'Anti-aging', 'Overnight repair'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates'],
    certifications: ['Dermatologically Tested', 'Clinically Proven'],
    ingredients: ['Retinol 0.3%', 'Peptides', 'Ceramides', 'Vitamin E'],
    size: '30g',
    specialFeatures: ['Encapsulated formula', 'Minimizes irritation', 'Overnight treatment'],
  },
  {
    name: 'AHA BHA 32% Exfoliating Peel',
    description: 'Texture, Uneven tone & Dead skin',
    detailedDescription: 'Professional-grade chemical exfoliant with 32% AHA (Glycolic Acid) and BHA (Salicylic Acid) that removes dead skin cells, smooths texture, and evens out skin tone. For weekly use.',
    price: 549,
    mrp: 699,
    discountPercentage: 21,
    category: 'Treatment',
    imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 98,
    keyBenefits: ['Smooths texture', 'Even skin tone', 'Removes dead skin', 'Professional-grade'],
    freeFrom: ['Fragrance', 'Parabens', 'Dyes'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Glycolic Acid', 'Salicylic Acid', 'Allantoin', 'Aloe Vera'],
    size: '30ml',
    specialFeatures: ['Weekly use', 'Intensive treatment', 'Suitable for experienced users'],
  },
  {
    name: 'Ceramide Repair Moisturizer',
    description: 'Barrier repair, Sensitivity & Dryness',
    detailedDescription: 'Barrier-repair moisturizer enriched with Ceramides, Cholesterol, and Fatty Acids that restores and strengthens the skin barrier. Ideal for sensitive, damaged, or dry skin.',
    price: 549,
    mrp: 699,
    discountPercentage: 21,
    category: 'Moisturizer',
    imageUrl: 'https://images.unsplash.com/photo-1556228863-7471bd74b6f0?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 178,
    keyBenefits: ['Repairs barrier', 'Soothes sensitivity', 'Reduces dryness', 'Strengthens skin'],
    freeFrom: ['Fragrance', 'Parabens', 'Alcohol', 'Sulphates'],
    certifications: ['Dermatologically Tested', 'Hypoallergenic'],
    ingredients: ['Ceramides', 'Cholesterol', 'Fatty Acids', 'Niacinamide'],
    size: '50g',
    specialFeatures: ['Barrier repair', 'Suitable for sensitive skin', 'Intensive repair'],
    bestSeller: true,
  },
  {
    name: 'Calming Clay Mask',
    description: 'Pores, Oiliness & Blackheads',
    detailedDescription: 'Purifying clay mask with Kaolin and Bentonite clay that deep cleans pores, absorbs excess oil, and removes blackheads. Leaves skin feeling clean and refreshed.',
    price: 399,
    mrp: 499,
    discountPercentage: 20,
    category: 'Mask',
    imageUrl: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=500&h=500&fit=crop',
    rating: 4.3,
    reviewCount: 112,
    keyBenefits: ['Deep cleans pores', 'Absorbs oil', 'Removes blackheads', 'Purifies skin'],
    freeFrom: ['Fragrance', 'Parabens', 'Artificial colors'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Kaolin Clay', 'Bentonite Clay', 'Aloe Vera', 'Glycerin'],
    size: '50g',
    specialFeatures: ['Purifying', 'Oil-absorbing', 'Deep cleansing'],
  },
  {
    name: 'Hydrating Toner',
    description: 'Hydration & Skin prep',
    detailedDescription: 'Alcohol-free hydrating toner with Rose Water and Niacinamide that soothes, hydrates, and prepares skin for better product absorption. Perfect for all skin types.',
    price: 299,
    mrp: 349,
    discountPercentage: 14,
    category: 'Toner',
    imageUrl: 'https://images.unsplash.com/photo-1583242193223-ecec3e8e3d91?w=500&h=500&fit=crop',
    rating: 4.2,
    reviewCount: 134,
    keyBenefits: ['Hydrates', 'Soothes skin', 'Prepares for absorption', 'Alcohol-free'],
    freeFrom: ['Alcohol', 'Fragrance', 'Parabens'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Rose Water', 'Niacinamide', 'Hyaluronic Acid', 'Glycerin'],
    size: '100ml',
    specialFeatures: ['Alcohol-free', 'Gentle', 'Suitable for sensitive skin'],
    bestSeller: true,
  },
  {
    name: 'Peptide Eye Cream',
    description: 'Dark circles, Fine lines & Puffiness',
    detailedDescription: 'Concentrated eye treatment with Matrixyl Peptides, Caffeine, and Hyaluronic Acid that targets dark circles, fine lines, and puffiness around the delicate eye area.',
    price: 599,
    mrp: 749,
    discountPercentage: 20,
    category: 'Treatment',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/products/HAPGA2_1200-1-min.png?crop=center&height=960&v=1646395962&width=640',
    rating: 4.4,
    reviewCount: 89,
    keyBenefits: ['Reduces dark circles', 'Minimizes fine lines', 'Reduces puffiness', 'Brightens'],
    freeFrom: ['Fragrance', 'Parabens', 'Retinol'],
    certifications: ['Dermatologically Tested', 'Ophthalmologically Tested'],
    ingredients: ['Matrixyl Peptides', 'Caffeine', 'Hyaluronic Acid', 'Vitamin K'],
    size: '15ml',
    specialFeatures: ['Safe for eye area', 'Non-irritating', 'Lightweight'],
    bestSeller: true,
  },
  {
    name: 'Soothing Cleansing Oil',
    description: 'Makeup removal, Gentle cleansing',
    detailedDescription: 'Dual-phase cleansing oil that effectively melts away makeup, sunscreen, and impurities while maintaining the skin\'s natural balance. Leaves skin soft and nourished.',
    price: 449,
    mrp: 549,
    discountPercentage: 18,
    category: 'Cleanser',
    imageUrl: 'https://images.unsplash.com/photo-1556228823-726483e96ada?w=500&h=500&fit=crop',
    rating: 4.3,
    reviewCount: 156,
    keyBenefits: ['Removes makeup', 'Gentle cleansing', 'Nourishes skin', 'Maintains balance'],
    freeFrom: ['Fragrance', 'Parabens', 'Mineral oil'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Jojoba Oil', 'Sunflower Oil', 'Vitamin E', 'Squalane'],
    size: '100ml',
    specialFeatures: ['Double cleansing', 'Non-comedogenic', 'Suitable for all skin types'],
  },
  {
    name: 'Antioxidant Day Cream',
    description: 'Protection, Brightening & Anti-aging',
    detailedDescription: 'Protective day cream enriched with Vitamin E and Green Tea Extract that shields skin from environmental damage while providing hydration and anti-aging benefits.',
    price: 599,
    mrp: 749,
    discountPercentage: 20,
    category: 'Moisturizer',
    imageUrl: 'https://images.unsplash.com/photo-1556228863-7471bd74b6f0?w=500&h=500&fit=crop',
    rating: 4.3,
    reviewCount: 145,
    keyBenefits: ['Environmental protection', 'Antioxidant defense', 'Hydration', 'Anti-aging'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Vitamin E', 'Green Tea Extract', 'Hyaluronic Acid', 'Niacinamide'],
    size: '50g',
    specialFeatures: ['SPF-compatible', 'Lightweight', 'Day-time use'],
  },
  {
    name: 'Glycolic Acid 7% Peel',
    description: 'Texture, Brightening & Exfoliation',
    detailedDescription: 'Professional-grade 7% Glycolic Acid peel for weekly use that reveals brighter, smoother skin by removing dead skin cells and improving texture.',
    price: 499,
    mrp: 649,
    discountPercentage: 23,
    category: 'Treatment',
    imageUrl: 'https://images.unsplash.com/photo-1608243803803-4c4c0055e3b1?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 112,
    keyBenefits: ['Brightens skin', 'Smooths texture', 'Weekly exfoliation', 'Professional-grade'],
    freeFrom: ['Fragrance', 'Parabens'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Glycolic Acid 7%', 'Allantoin', 'Aloe Vera', 'Glycerin'],
    size: '30ml',
    specialFeatures: ['Weekly treatment', 'Beginner-friendly', 'Suitable for most skin types'],
  },
  {
    name: 'Sheet Mask Set (5 pcs)',
    description: 'Hydration & Instant glow',
    detailedDescription: 'Set of 5 hydrating sheet masks infused with Hyaluronic Acid that provide instant hydration, glow, and plumpness. Perfect for weekly pampering sessions.',
    price: 299,
    mrp: 399,
    discountPercentage: 25,
    category: 'Mask',
    imageUrl: 'https://images.unsplash.com/photo-1617996080152-bd25724c90d6?w=500&h=500&fit=crop',
    rating: 4.2,
    reviewCount: 234,
    keyBenefits: ['Instant hydration', 'Immediate glow', 'Skin plumping', 'Relaxing'],
    freeFrom: ['Fragrance', 'Parabens', 'Alcohol'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Hyaluronic Acid', 'Glycerin', 'Aloe Vera', 'Niacinamide'],
    size: '5 pieces',
    specialFeatures: ['Single-use', 'Convenient', 'Travel-friendly'],
  },
  {
    name: 'Salicylic Acid 2% Cleanser',
    description: 'Acne, Oiliness & Breakouts',
    detailedDescription: '2% Salicylic Acid cleanser specifically formulated for acne-prone skin. Unclogs pores, prevents breakouts, and controls excess oil production without over-drying.',
    price: 349,
    mrp: 399,
    discountPercentage: 13,
    category: 'Cleanser',
    imageUrl: 'https://images.unsplash.com/photo-1608243810491-8b3f279ee840?w=500&h=500&fit=crop',
    rating: 4.4,
    reviewCount: 198,
    keyBenefits: ['Fights acne', 'Unclogs pores', 'Controls oil', 'Prevents breakouts'],
    freeFrom: ['Fragrance', 'Sulphates', 'Parabens'],
    certifications: ['Dermatologically Tested', 'Non-comedogenic'],
    ingredients: ['Salicylic Acid 2%', 'Tea Tree Extract', 'Glycerin', 'Allantoin'],
    size: '100ml',
    specialFeatures: ['Acne-fighting', 'Non-drying', 'Suitable for oily skin'],
  },
  {
    name: 'Caffeine Eye Serum',
    description: 'Puffiness, Dark circles & Fatigue',
    detailedDescription: 'Fast-acting eye serum with Caffeine and Peptides that reduces puffiness, minimizes dark circles, and combats signs of fatigue in the delicate eye area.',
    price: 449,
    mrp: 549,
    discountPercentage: 18,
    category: 'Serum',
    imageUrl: 'https://images.unsplash.com/photo-1631196428422-2b6db4f0aa2c?w=500&h=500&fit=crop',
    rating: 4.3,
    reviewCount: 167,
    keyBenefits: ['Reduces puffiness', 'Minimizes dark circles', 'Combats fatigue', 'Quick action'],
    freeFrom: ['Fragrance', 'Parabens', 'Retinol'],
    certifications: ['Ophthalmologically Tested'],
    ingredients: ['Caffeine', 'Peptides', 'Hyaluronic Acid', 'Vitamin K'],
    size: '15ml',
    specialFeatures: ['Safe for eye area', 'Fast-absorbing', 'Non-irritating'],
  },
  {
    name: 'Probiotic Moisturizer',
    description: 'Balance, Sensitivity & Barrier health',
    detailedDescription: 'Skin-balancing moisturizer with Probiotics that strengthens the skin barrier, calms irritation, and maintains optimal skin microbiome health.',
    price: 649,
    mrp: 799,
    discountPercentage: 19,
    category: 'Moisturizer',
    imageUrl: 'https://images.unsplash.com/photo-1556228863-7471bd74b6f0?w=500&h=500&fit=crop',
    rating: 4.4,
    reviewCount: 123,
    keyBenefits: ['Balances skin', 'Strengthens barrier', 'Calms irritation', 'Microbiome health'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates'],
    certifications: ['Dermatologically Tested', 'Clinically Proven'],
    ingredients: ['Probiotics', 'Ceramides', 'Niacinamide', 'Squalane'],
    size: '50g',
    specialFeatures: ['Microbiome-friendly', 'Suitable for sensitive skin', 'Barrier support'],
  },
  {
    name: 'AHA Toner',
    description: 'Texture, Brightening & Daily exfoliation',
    detailedDescription: 'Gentle exfoliating toner with Lactic Acid (AHA) that refines skin texture, brightens complexion, and provides daily mild exfoliation suitable for regular use.',
    price: 399,
    mrp: 499,
    discountPercentage: 20,
    category: 'Toner',
    imageUrl: 'https://images.unsplash.com/photo-1583242193223-ecec3e8e3d91?w=500&h=500&fit=crop',
    rating: 4.3,
    reviewCount: 145,
    keyBenefits: ['Refines texture', 'Brightens skin', 'Daily exfoliation', 'Gentle formula'],
    freeFrom: ['Alcohol', 'Fragrance', 'Parabens'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Lactic Acid', 'Hyaluronic Acid', 'Glycerin', 'Aloe Vera'],
    size: '100ml',
    specialFeatures: ['Daily use', 'Gentle exfoliation', 'Beginner-friendly'],
  },
  {
    name: 'Tinted Sunscreen SPF 30',
    description: 'Sun protection & Coverage',
    detailedDescription: 'Lightweight tinted sunscreen with SPF 30 that provides UV protection while offering light coverage. Non-greasy formula perfect for daily wear.',
    price: 449,
    mrp: 549,
    discountPercentage: 18,
    category: 'Sunscreen',
    imageUrl: 'https://images.unsplash.com/photo-1556228837-c10d1766dc24?w=500&h=500&fit=crop',
    rating: 4.3,
    reviewCount: 178,
    keyBenefits: ['SPF 30 protection', 'Light coverage', 'Non-greasy', 'Daily wear'],
    freeFrom: ['Fragrance', 'Parabens', 'Oxybenzone'],
    certifications: ['PA+++', 'Non-comedogenic'],
    ingredients: ['Zinc Oxide', 'Iron Oxides', 'Titanium Dioxide', 'Vitamin E'],
    size: '50g',
    specialFeatures: ['Tinted', 'Lightweight', 'Buildable coverage'],
  },
  {
    name: 'Azelaic Acid 10% Serum',
    description: 'Acne, Hyperpigmentation & Redness',
    detailedDescription: 'Multi-benefit serum with 10% Azelaic Acid that treats acne, reduces hyperpigmentation, and calms redness. Gentle yet effective formula suitable for sensitive skin.',
    price: 499,
    mrp: 649,
    discountPercentage: 23,
    category: 'Serum',
    imageUrl: 'https://images.unsplash.com/photo-1556228578-94684598cc71?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 156,
    keyBenefits: ['Treats acne', 'Reduces hyperpigmentation', 'Calms redness', 'Gentle formula'],
    freeFrom: ['Fragrance', 'Parabens', 'Alcohol'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Azelaic Acid 10%', 'Niacinamide', 'Allantoin', 'Glycerin'],
    size: '30ml',
    specialFeatures: ['Suitable for sensitive skin', 'Multi-benefit', 'Gentle yet effective'],
    bestSeller: true,
  },
  {
    name: 'Overnight Repair Mask',
    description: 'Repair, Hydration & Recovery',
    detailedDescription: 'Intensive overnight repair mask with Peptides and Ceramides that works while you sleep to repair, hydrate, and rejuvenate skin. Wake up to plump, glowing skin.',
    price: 699,
    mrp: 899,
    discountPercentage: 22,
    category: 'Mask',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/products/HAPGA2_1200-1-min.png?crop=center&height=960&v=1646395962&width=640',
    rating: 4.4,
    reviewCount: 134,
    keyBenefits: ['Overnight repair', 'Intense hydration', 'Skin rejuvenation', 'Wake-up glow'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates'],
    certifications: ['Dermatologically Tested', 'Clinically Proven'],
    ingredients: ['Peptides', 'Ceramides', 'Hyaluronic Acid', 'Vitamin E'],
    size: '50g',
    specialFeatures: ['Overnight treatment', 'Intensive repair', 'Weekly use'],
    bestSeller: true,
  },
  {
    name: 'Multi-Peptide Hair Serum',
    description: 'Hair growth & scalp health',
    detailedDescription: 'Advanced multi-peptide hair serum that promotes stronger, thicker hair growth while nourishing the scalp. Suitable for all hair types.',
    price: 549,
    mrp: 599,
    discountPercentage: 8,
    category: 'Hair Care',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-8e8ce23d8cb1?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 203,
    keyBenefits: ['Hair growth', 'Scalp health', 'Thicker hair', 'Strengthens follicles'],
    freeFrom: ['Fragrance', 'Parabens', 'Minoxidil'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Peptides', 'Biotin', 'Zinc PCA', 'Glycerin'],
    size: '60ml',
    specialFeatures: ['Non-greasy', 'Quick absorption', 'Daily use'],
    bestSeller: true,
  },
  {
    name: 'Vitamin B5 Moisturizer',
    description: 'Hydration & Barrier repair',
    detailedDescription: 'Lightweight moisturizer with 10% Vitamin B5 that provides deep hydration and strengthens the skin barrier. Perfect for daily use.',
    price: 399,
    mrp: 449,
    discountPercentage: 11,
    category: 'Moisturizer',
    imageUrl: 'https://images.unsplash.com/photo-1556228863-7471bd74b6f0?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 267,
    keyBenefits: ['Deep hydration', 'Barrier repair', 'Non-greasy', 'Quick absorption'],
    freeFrom: ['Fragrance', 'Parabens', 'Alcohol'],
    certifications: ['Dermatologically Tested', 'Non-comedogenic'],
    ingredients: ['Vitamin B5 10%', 'Glycerin', 'Ceramides', 'Niacinamide'],
    size: '50g',
    specialFeatures: ['Lightweight', 'Fast-absorbing', 'Suitable for all skin types'],
    bestSeller: true,
  },
  {
    name: 'Retinol 0.1% Serum',
    description: 'Anti-aging & Skin renewal',
    detailedDescription: 'Gentle yet effective serum with 0.1% encapsulated Retinol that reduces fine lines, improves skin texture, and promotes cell renewal.',
    price: 449,
    mrp: 549,
    discountPercentage: 18,
    category: 'Serum',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/products/SalicylicAcid2_1200-1-min.png?crop=center&height=960&v=1646458899&width=640',
    rating: 4.5,
    reviewCount: 189,
    keyBenefits: ['Reduces fine lines', 'Improves texture', 'Skin renewal', 'Anti-aging'],
    freeFrom: ['Fragrance', 'Parabens'],
    certifications: ['Dermatologically Tested', 'Clinically Proven'],
    ingredients: ['Retinol 0.1%', 'Peptides', 'Ceramides', 'Vitamin E'],
    size: '30ml',
    specialFeatures: ['Encapsulated formula', 'Beginner-friendly', 'Overnight use'],
    bestSeller: true,
  },
  {
    name: 'Light Fluid SPF 50 Sunscreen',
    description: 'Sun protection & UV damage',
    detailedDescription: 'Ultra-lightweight SPF 50 sunscreen with a fluid texture that provides broad-spectrum protection without any greasy residue.',
    price: 474,
    mrp: 499,
    discountPercentage: 5,
    category: 'Sunscreen',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SPF50New.jpg?crop=center&height=960&v=1756795782&width=640',
    rating: 4.7,
    reviewCount: 312,
    keyBenefits: ['SPF 50 protection', 'Ultra-lightweight', 'No white cast', 'Non-greasy'],
    freeFrom: ['Fragrance', 'Parabens', 'Oxybenzone'],
    certifications: ['PA++++', 'Water-resistant'],
    ingredients: ['Zinc Oxide', 'Titanium Dioxide', 'Niacinamide', 'Hyaluronic Acid'],
    size: '50g',
    specialFeatures: ['Fluid texture', 'Water-resistant', 'Perfect for oily skin'],
    bestSeller: true,
  },
  {
    name: 'COQ10 Serum',
    description: 'Anti-aging & Skin firmness',
    detailedDescription: 'Powerful anti-aging serum with Coenzyme Q10 that fights free radicals, improves skin elasticity, and reduces signs of aging.',
    price: 599,
    mrp: 699,
    discountPercentage: 14,
    category: 'Serum',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/products/HAPGA2_1200-1-min.png?crop=center&height=960&v=1646395962&width=640',
    rating: 4.4,
    reviewCount: 156,
    keyBenefits: ['Anti-aging', 'Improves elasticity', 'Fights free radicals', 'Firms skin'],
    freeFrom: ['Fragrance', 'Parabens'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Coenzyme Q10', 'Vitamin E', 'Peptides', 'Glycerin'],
    size: '30ml',
    specialFeatures: ['Antioxidant-rich', 'Suitable for mature skin', 'Daily use'],
    bestSeller: true,
  },
  {
    name: 'Centella + B5 Reversal Serum',
    description: 'Redness & Sensitivity repair',
    detailedDescription: 'Calming serum with Centella Asiatica and Vitamin B5 that soothes redness, repairs sensitivity, and strengthens the skin barrier.',
    price: 549,
    mrp: 649,
    discountPercentage: 15,
    category: 'Serum',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/products/Nia5BodyLotion1100-1-min.png?crop=center&height=960&v=1649958609&width=640',
    rating: 4.6,
    reviewCount: 201,
    keyBenefits: ['Reduces redness', 'Soothes sensitivity', 'Barrier repair', 'Calming'],
    freeFrom: ['Fragrance', 'Parabens', 'Alcohol'],
    certifications: ['Dermatologically Tested', 'Hypoallergenic'],
    ingredients: ['Centella Asiatica', 'Vitamin B5', 'Niacinamide', 'Glycerin'],
    size: '30ml',
    specialFeatures: ['Anti-inflammatory', 'Suitable for sensitive skin', 'Gentle formula'],
    bestSeller: true,
  },
  {
    name: 'Kojic Acid De-tan Face Serum',
    description: 'Tan removal & Brightening',
    detailedDescription: 'De-tanning serum with Kojic Acid that removes tan, brightens skin tone, and evens out complexion for a radiant glow.',
    price: 449,
    mrp: 549,
    discountPercentage: 18,
    category: 'Serum',
    imageUrl: 'https://images.unsplash.com/photo-1556228578-94684598cc71?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 234,
    keyBenefits: ['Removes tan', 'Brightens skin', 'Even tone', 'Radiant glow'],
    freeFrom: ['Fragrance', 'Parabens'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Kojic Acid', 'Arbutin', 'Lactic Acid', 'Glycerin'],
    size: '30ml',
    specialFeatures: ['De-tanning', 'Brightening formula', 'Suitable for all skin types'],
  },
  {
    name: 'Marula Oil 05% Cleansing Oil',
    description: 'Makeup removal & Deep cleansing',
    detailedDescription: 'Luxurious cleansing oil with 5% Marula Oil that gently removes makeup and impurities while nourishing the skin.',
    price: 569,
    mrp: 599,
    discountPercentage: 5,
    category: 'Cleanser',
    imageUrl: 'https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SalicylicCleanserNew.jpg?crop=center&height=1260&v=1756796206&width=840',
    rating: 4.4,
    reviewCount: 178,
    keyBenefits: ['Removes makeup', 'Deep cleansing', 'Nourishes skin', 'Marula oil'],
    freeFrom: ['Fragrance', 'Parabens', 'Mineral oil'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Marula Oil 5%', 'Caprylic Triglyceride', 'Vitamin E', 'Squalane'],
    size: '100ml',
    specialFeatures: ['Double cleansing', 'Non-comedogenic', 'Suitable for all skin types'],
    bestSeller: true,
  },
  {
    name: 'Plant Derived Squalane Face Oil',
    description: 'Hydration & Nourishment',
    detailedDescription: 'Lightweight face oil with 100% plant-derived Squalane that provides intense hydration and nourishment without feeling heavy.',
    price: 549,
    mrp: 649,
    discountPercentage: 15,
    category: 'Moisturizer',
    imageUrl: 'https://images.unsplash.com/photo-1556228863-7471bd74b6f0?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 145,
    keyBenefits: ['Intense hydration', 'Lightweight', 'Non-greasy', 'Skin nourishment'],
    freeFrom: ['Fragrance', 'Parabens'],
    certifications: ['Dermatologically Tested', 'Vegan'],
    ingredients: ['Plant-derived Squalane 100%', 'Vitamin E'],
    size: '30ml',
    specialFeatures: ['100% Squalane', 'Non-comedogenic', 'Suitable for all skin types'],
    bestSeller: true,
  },
  {
    name: 'Copper Peptide + PDRN 1.25% Serum',
    description: 'Anti-aging & Skin repair',
    detailedDescription: 'Advanced anti-aging serum with Copper Peptides and PDRN that promotes skin repair, reduces wrinkles, and improves skin elasticity.',
    price: 664,
    mrp: 699,
    discountPercentage: 5,
    category: 'Serum',
    imageUrl: 'https://images.unsplash.com/photo-1556228578-94684598cc71?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 167,
    keyBenefits: ['Anti-aging', 'Skin repair', 'Reduces wrinkles', 'Improves elasticity'],
    freeFrom: ['Fragrance', 'Parabens'],
    certifications: ['Dermatologically Tested', 'Clinically Proven'],
    ingredients: ['Copper Peptides', 'PDRN 1.25%', 'Hyaluronic Acid', 'Peptides'],
    size: '30ml',
    specialFeatures: ['Advanced formula', 'Overnight repair', 'Professional-grade'],
  },
  // Baby Care Products
  {
    name: 'Ceramide & Vitamin B5 Delicate Cleanser',
    description: 'Gentle cleansing for sensitive baby skin',
    detailedDescription: 'Ultra-gentle cleanser enriched with Ceramides and Vitamin B5 specifically formulated for babies delicate skin. Free from harsh chemicals, this pH-balanced cleanser maintains the natural skin barrier.',
    price: 569,
    mrp: 599,
    discountPercentage: 5,
    category: 'Baby Care',
    imageUrl: 'https://images.unsplash.com/photo-1608243803803-4c4c0055e3b1?w=500&h=500&fit=crop',
    rating: 4.7,
    reviewCount: 234,
    keyBenefits: ['Ultra-gentle cleansing', 'Maintains skin barrier', 'pH-balanced', 'Hypoallergenic'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates', 'Dyes'],
    certifications: ['Pediatrician Tested', 'Hypoallergenic'],
    ingredients: ['Ceramides', 'Vitamin B5', 'Glycerin', 'Aloe Vera'],
    size: '200ml',
    specialFeatures: ['Tear-free', 'Suitable for newborns', 'Daily use'],
    bestSeller: true,
  },
  {
    name: 'Ceramide & Squalane Nourishing Lotion',
    description: 'Deep hydration and nourishment',
    detailedDescription: 'Rich, non-greasy lotion with Ceramides and Squalane that provides 24-hour hydration and nourishment. Perfect for daily moisturizing of babies delicate skin.',
    price: 854,
    mrp: 899,
    discountPercentage: 5,
    category: 'Baby Care',
    imageUrl: 'https://images.unsplash.com/photo-1608243810491-8b3f279ee840?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 189,
    keyBenefits: ['24-hour hydration', 'Non-greasy', 'Deep nourishment', 'Lightweight formula'],
    freeFrom: ['Fragrance', 'Parabens', 'Mineral oil', 'Phthalates'],
    certifications: ['Pediatrician Tested', 'Clinically Proven'],
    ingredients: ['Ceramides', 'Squalane', 'Vitamin E', 'Glycerin'],
    size: '200ml',
    specialFeatures: ['Quick absorption', 'Suitable for sensitive skin', 'Daily moisturizing'],
    bestSeller: true,
  },
  {
    name: 'Zinc Oxide + B5 Healing Ointment',
    description: 'Diaper rash and skin irritation relief',
    detailedDescription: 'Protective healing ointment with 20% Zinc Oxide and Vitamin B5 that forms a barrier to protect against diaper rash and soothe irritated skin.',
    price: 379,
    mrp: 399,
    discountPercentage: 5,
    category: 'Baby Care',
    imageUrl: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=500&h=500&fit=crop',
    rating: 4.8,
    reviewCount: 312,
    keyBenefits: ['Prevents diaper rash', 'Soothes irritation', 'Waterproof barrier', 'Fast healing'],
    freeFrom: ['Fragrance', 'Parabens', 'Dyes'],
    certifications: ['Pediatrician Tested', 'Clinically Proven'],
    ingredients: ['Zinc Oxide 20%', 'Vitamin B5', 'Petrolatum', 'Dimethicone'],
    size: '50g',
    specialFeatures: ['Waterproof', 'Long-lasting protection', 'Non-irritating'],
  },
  {
    name: 'Provitamin D3 Massage Oil',
    description: 'Calming massage and moisturization',
    detailedDescription: 'Nourishing massage oil enriched with Provitamin D3 and natural oils that moisturizes and softens baby skin while providing a calming massage experience.',
    price: 569,
    mrp: 599,
    discountPercentage: 5,
    category: 'Baby Care',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-d244851f3776?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 156,
    keyBenefits: ['Deep moisturization', 'Calming massage', 'Softens skin', 'Vitamin D3'],
    freeFrom: ['Fragrance', 'Parabens', 'Mineral oil'],
    certifications: ['Pediatrician Tested'],
    ingredients: ['Provitamin D3', 'Coconut Oil', 'Jojoba Oil', 'Vitamin E'],
    size: '100ml',
    specialFeatures: ['Non-sticky', 'Easy application', 'Natural ingredients'],
  },
  {
    name: 'Baby Shampoo & Body Wash',
    description: 'Gentle all-in-one cleansing',
    detailedDescription: 'Mild 2-in-1 shampoo and body wash specially formulated for babies delicate skin and hair. Tear-free, hypoallergenic formula.',
    price: 379,
    mrp: 399,
    discountPercentage: 5,
    category: 'Baby Care',
    imageUrl: 'https://images.unsplash.com/photo-1608243810491-8b3f279ee840?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 245,
    keyBenefits: ['2-in-1 formula', 'Tear-free', 'Hypoallergenic', 'Gentle cleansing'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates'],
    certifications: ['Pediatrician Tested', 'Hypoallergenic'],
    ingredients: ['Aloe Vera', 'Chamomile Extract', 'Glycerin', 'Vitamin E'],
    size: '200ml',
    specialFeatures: ['2-in-1', 'Tear-free', 'Suitable for newborns'],
  },
  {
    name: 'Baby Powder with Calendula',
    description: 'Gentle powder for delicate skin',
    detailedDescription: 'Soft baby powder enriched with Calendula that keeps skin dry and comfortable while preventing irritation.',
    price: 449,
    mrp: 479,
    discountPercentage: 6,
    category: 'Baby Care',
    imageUrl: 'https://images.unsplash.com/photo-1583242193223-ecec3e8e3d91?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 178,
    keyBenefits: ['Keeps skin dry', 'Prevents irritation', 'Gentle formula', 'Calendula'],
    freeFrom: ['Talc', 'Fragrance', 'Parabens'],
    certifications: ['Pediatrician Tested'],
    ingredients: ['Corn Starch', 'Calendula Extract', 'Zinc Oxide', 'Aloe Vera'],
    size: '100g',
    specialFeatures: ['Natural ingredients', 'Talc-free', 'Gentle on skin'],
  },
  // Hair Care Products
  {
    name: 'Anti Dandruff Shampoo 3.5%',
    description: 'Effective dandruff control and scalp health',
    detailedDescription: 'Medicated anti-dandruff shampoo with 3.5% Zinc Pyrithione that effectively controls dandruff, reduces scalp irritation, and removes impurities. Gentle yet effective formula.',
    price: 418,
    mrp: 440,
    discountPercentage: 5,
    category: 'Hair Care',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-c6c7958d374f?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 267,
    keyBenefits: ['Controls dandruff', 'Reduces irritation', 'Cleanses scalp', 'Gentle formula'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Zinc Pyrithione 3.5%', 'Tea Tree Extract', 'Glycerin', 'Aloe Vera'],
    size: '200ml',
    specialFeatures: ['Medicated', 'Weekly use', 'Suitable for all hair types'],
    bestSeller: true,
  },
  {
    name: 'Hair Growth Serum with Capixyl 10%',
    description: 'Promotes hair growth and reduces hair fall',
    detailedDescription: 'Advanced hair growth serum with 10% Capixyl that strengthens hair roots, reduces hair fall, and promotes new hair growth. Clinically proven formula.',
    price: 569,
    mrp: 599,
    discountPercentage: 5,
    category: 'Hair Care',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-8e8ce23d8cb1?w=500&h=500&fit=crop',
    rating: 4.4,
    reviewCount: 198,
    keyBenefits: ['Reduces hair fall', 'Promotes growth', 'Strengthens roots', 'Longer hair'],
    freeFrom: ['Fragrance', 'Parabens', 'Minoxidil'],
    certifications: ['Dermatologically Tested', 'Clinically Proven'],
    ingredients: ['Capixyl 10%', 'Peptides', 'Biotin', 'Glycerin'],
    size: '60ml',
    specialFeatures: ['Non-greasy', 'Quick absorption', 'Daily use'],
    bestSeller: true,
  },
  {
    name: 'Peptide + Carnitine Hair Mask',
    description: 'Repair and nourishment for damaged hair',
    detailedDescription: 'Intensive hair repair mask with Peptides and Carnitine that deeply nourishes, repairs damage, and restores hair health. Ideal for damaged and frizzy hair.',
    price: 699,
    mrp: 749,
    discountPercentage: 7,
    category: 'Hair Care',
    imageUrl: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 145,
    keyBenefits: ['Repairs damage', 'Reduces frizz', 'Deep nourishment', 'Smooths hair'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Peptides', 'Carnitine', 'Keratin', 'Argan Oil'],
    size: '200g',
    specialFeatures: ['Weekly treatment', 'Intensive repair', 'Suitable for all hair types'],
  },
  {
    name: 'Maleic Acid Smoothing Shampoo',
    description: 'Smooths frizzy hair and adds shine',
    detailedDescription: 'Smoothing shampoo with Maleic Acid that tames frizz, adds shine, and makes hair more manageable. pH-balanced formula for daily use.',
    price: 379,
    mrp: 399,
    discountPercentage: 5,
    category: 'Hair Care',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-c6c7958d374f?w=500&h=500&fit=crop',
    rating: 4.3,
    reviewCount: 178,
    keyBenefits: ['Smooths frizz', 'Adds shine', 'Manageable hair', 'pH-balanced'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Maleic Acid', 'Keratin', 'Glycerin', 'Vitamin E'],
    size: '250ml',
    specialFeatures: ['Daily use', 'Smooth finish', 'Suitable for frizzy hair'],
  },
  {
    name: 'Biotin Strengthening Shampoo',
    description: 'Strengthens and thickens hair',
    detailedDescription: 'Fortifying shampoo with Biotin and Keratin that strengthens hair from roots, adds volume, and reduces breakage. Perfect for thinning and weak hair.',
    price: 449,
    mrp: 479,
    discountPercentage: 6,
    category: 'Hair Care',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-c6c7958d374f?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 203,
    keyBenefits: ['Strengthens hair', 'Adds volume', 'Reduces breakage', 'Thicker hair'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Biotin', 'Keratin', 'Vitamin E', 'Glycerin'],
    size: '250ml',
    specialFeatures: ['Volumizing', 'Daily use', 'Suitable for all hair types'],
  },
  {
    name: 'Keratin Repair Conditioner',
    description: 'Repair & Smoothness',
    detailedDescription: 'Intensive keratin conditioner that repairs damaged hair, reduces frizz, and leaves hair smooth and manageable.',
    price: 499,
    mrp: 549,
    discountPercentage: 9,
    category: 'Hair Care',
    imageUrl: 'https://images.unsplash.com/photo-1608243810491-8b3f279ee840?w=500&h=500&fit=crop',
    rating: 4.4,
    reviewCount: 167,
    keyBenefits: ['Repairs damage', 'Reduces frizz', 'Smooth hair', 'Manageable'],
    freeFrom: ['Fragrance', 'Parabens', 'Sulphates'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Keratin', 'Argan Oil', 'Shea Butter', 'Glycerin'],
    size: '250ml',
    specialFeatures: ['Deep conditioning', 'Repair formula', 'Suitable for damaged hair'],
  },
  {
    name: 'Scalp Serum with Peptides',
    description: 'Scalp health & Hair growth',
    detailedDescription: 'Targeted scalp serum with Peptides that nourishes the scalp, promotes hair growth, and maintains a healthy scalp environment.',
    price: 649,
    mrp: 699,
    discountPercentage: 7,
    category: 'Hair Care',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-8e8ce23d8cb1?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 134,
    keyBenefits: ['Scalp health', 'Hair growth', 'Nourishes scalp', 'Strengthens roots'],
    freeFrom: ['Fragrance', 'Parabens', 'Minoxidil'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Peptides', 'Zinc PCA', 'Ginseng Extract', 'Glycerin'],
    size: '50ml',
    specialFeatures: ['Scalp-focused', 'Non-greasy', 'Daily use'],
  },
  {
    name: 'Hair Growth Oil with Rosemary',
    description: 'Hair growth & Nourishment',
    detailedDescription: 'Natural hair growth oil with Rosemary and essential nutrients that stimulates follicles and promotes healthy hair growth.',
    price: 569,
    mrp: 599,
    discountPercentage: 5,
    category: 'Hair Care',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-8e8ce23d8cb1?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 189,
    keyBenefits: ['Hair growth', 'Stimulates follicles', 'Natural ingredients', 'Nourishes scalp'],
    freeFrom: ['Fragrance', 'Parabens', 'Minoxidil'],
    certifications: ['Dermatologically Tested'],
    ingredients: ['Rosemary Oil', 'Castor Oil', 'Vitamin E', 'Biotin'],
    size: '100ml',
    specialFeatures: ['Natural oil blend', 'Warm oil treatment', 'Weekly use'],
  },
];

const seedProducts = async () => {
  try {
    await connectDB();
    await Product.deleteMany(); // optional: clear old data
    await Product.insertMany(products);
    console.log("✅ Data seeded successfully!");
    process.exit();
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  }
};

seedProducts();